import { Car, Region } from './types';

export const regions: Region[] = [
  { id: '1', name: 'Dar es Salaam', carCount: 45 },
  { id: '2', name: 'Arusha', carCount: 23 },
  { id: '3', name: 'Dodoma', carCount: 18 },
  { id: '4', name: 'Mbeya', carCount: 12 },
  { id: '5', name: 'Mwanza', carCount: 15 },
  { id: '6', name: 'Morogoro', carCount: 8 },
  { id: '7', name: 'Tanga', carCount: 10 },
  { id: '8', name: 'Zanzibar', carCount: 7 },
];

export const brands = ['Toyota', 'Nissan', 'BMW', 'Mercedes-Benz', 'Honda', 'Mitsubishi', 'Suzuki', 'Hyundai', 'Land Rover', 'Volkswagen'];

const carImages = [
  'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
  'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80',
  'https://images.unsplash.com/photo-1549317661-bd32c8ce0afa?w=800&q=80',
  'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80',
  'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80',
  'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80',
  'https://images.unsplash.com/photo-1533473359331-2969b6ae73fc?w=800&q=80',
  'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80',
];

export const cars: Car[] = [
  {
    id: '1',
    title: 'Toyota Land Cruiser V8',
    brand: 'Toyota',
    model: 'Land Cruiser',
    year: 2020,
    price: 185000000,
    mileage: 32000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    condition: 'Used',
    description: 'Excellent condition Toyota Land Cruiser V8 with full service history. Leather interior, sunroof, and advanced safety features.',
    status: 'Available',
    region: 'Dar es Salaam',
    images: [carImages[0], carImages[1], carImages[2]],
  },
  {
    id: '2',
    title: 'BMW X5 xDrive40i',
    brand: 'BMW',
    model: 'X5',
    year: 2021,
    price: 145000000,
    mileage: 18000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    condition: 'Used',
    description: 'Premium BMW X5 with M Sport package. Panoramic roof, heads-up display, and Harman Kardon sound system.',
    status: 'Available',
    region: 'Arusha',
    images: [carImages[3], carImages[4], carImages[5]],
  },
  {
    id: '3',
    title: 'Mercedes-Benz GLE 350',
    brand: 'Mercedes-Benz',
    model: 'GLE',
    year: 2019,
    price: 128000000,
    mileage: 45000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    condition: 'Used',
    description: 'Luxurious Mercedes-Benz GLE with AMG styling. Full leather, 360 camera, and adaptive cruise control.',
    status: 'Available',
    region: 'Dar es Salaam',
    images: [carImages[6], carImages[7], carImages[0]],
  },
  {
    id: '4',
    title: 'Toyota Hilux Double Cab',
    brand: 'Toyota',
    model: 'Hilux',
    year: 2022,
    price: 92000000,
    mileage: 12000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    condition: 'Used',
    description: 'Nearly new Toyota Hilux with leather seats, touchscreen infotainment, and powerful diesel engine.',
    status: 'Available',
    region: 'Mwanza',
    images: [carImages[1], carImages[3], carImages[5]],
  },
  {
    id: '5',
    title: 'Nissan X-Trail',
    brand: 'Nissan',
    model: 'X-Trail',
    year: 2020,
    price: 58000000,
    mileage: 38000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    condition: 'Used',
    description: 'Family-friendly Nissan X-Trail with 7 seats, cruise control, and reverse camera.',
    status: 'Available',
    region: 'Dodoma',
    images: [carImages[2], carImages[4], carImages[6]],
  },
  {
    id: '6',
    title: 'Honda CR-V Touring',
    brand: 'Honda',
    model: 'CR-V',
    year: 2021,
    price: 72000000,
    mileage: 22000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    condition: 'Used',
    description: 'Top spec Honda CR-V Touring with Honda Sensing suite, wireless charging, and premium audio.',
    status: 'Reserved',
    region: 'Arusha',
    images: [carImages[5], carImages[7], carImages[1]],
  },
  {
    id: '7',
    title: 'Suzuki Jimny Sierra',
    brand: 'Suzuki',
    model: 'Jimny',
    year: 2023,
    price: 48000000,
    mileage: 5000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    condition: 'New',
    description: 'Brand new Suzuki Jimny Sierra. Perfect for off-road adventures. 4WD with part-time transfer case.',
    status: 'Available',
    region: 'Mbeya',
    images: [carImages[4], carImages[0], carImages[2]],
  },
  {
    id: '8',
    title: 'Toyota RAV4 Hybrid',
    brand: 'Toyota',
    model: 'RAV4',
    year: 2022,
    price: 88000000,
    mileage: 15000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    condition: 'Used',
    description: 'Eco-friendly Toyota RAV4 Hybrid with excellent fuel economy. Safety Sense 2.0 included.',
    status: 'Available',
    region: 'Dar es Salaam',
    images: [carImages[7], carImages[3], carImages[6]],
  },
  {
    id: '9',
    title: 'Hyundai Tucson',
    brand: 'Hyundai',
    model: 'Tucson',
    year: 2023,
    price: 65000000,
    mileage: 8000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    condition: 'New',
    description: 'All-new Hyundai Tucson with stunning design. Digital cockpit, Bose audio, and blind spot monitoring.',
    status: 'Available',
    region: 'Morogoro',
    images: [carImages[6], carImages[2], carImages[4]],
  },
  {
    id: '10',
    title: 'Land Rover Defender 110',
    brand: 'Land Rover',
    model: 'Defender',
    year: 2021,
    price: 210000000,
    mileage: 28000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    condition: 'Used',
    description: 'Iconic Land Rover Defender 110 with off-road capability. Air suspension, terrain response, and Wade sensing.',
    status: 'Available',
    region: 'Tanga',
    images: [carImages[0], carImages[5], carImages[7]],
  },
];

export function formatPrice(price: number): string {
  return `TZS ${(price / 1000000).toFixed(0)}M`;
}

export function formatPriceFull(price: number): string {
  return new Intl.NumberFormat('en-TZ', {
    style: 'currency',
    currency: 'TZS',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}
